Something modifications to guidebook
SivilTaram/BUAAOS-guide-book pull request #9
Opened 2017-02-27 08:51 UTC by Jueast

Well,
It cannot merge automatically, please check it.

2017-02-28 14:54 UTC, sighingnow commented
HI Jueast, thanks for your contribution. Please rebase the change locally and upload a replacement commit.

2017-02-28 14:56 UTC, sighingnow commented
cc @fzyz999 @SivilTaram in case of you don't get notification.

2017-02-28 14:59 UTC, sighingnow requested changes
Please rebase to our master branch and resolve conflicts locally.

2017-02-28 15:06 UTC, sighingnow requested changes

2017-02-28 15:06 UTC, sighingnow commented on guide-book/chapters/4-syscall.tex
> +首先我们看向sys\_mem\_alloc。这个函数的主要功能是分配内存，简单的说来，用户程序可以通过这个系统调用给该程序所允许的虚拟内存空间内存分配实际的物理内存，需要用到一些我们之前在pmap.c中所定义的函数
Should be "简单来说" rather than "简单的说来".

2017-02-28 15:06 UTC, sighingnow commented on guide-book/chapters/4-syscall.tex
> +关于内存的还有一个函数：sys\_mem\_unmap,正如字面意义所显示的，这个系统调用的功能是解除某个进程地址空间虚拟内存和物理内存之间的映射关系。
Please use full width comma in ordinary text (after the sys\_mem\_unmap).

2017-03-02 05:34 UTC, Jueast commented
I have solve the conflicts manually without rebasing.

2017-03-02 09:53 UTC, sighingnow approved these changes

2017-03-02 09:54 UTC, merged

2017-03-02 09:55 UTC, sighingnow commented
Thanks, @Jueast ,merged now.

2017-03-15 01:47 UTC, SivilTaram commented
Sorry for being late. I will take a loot at it 👍